config:
  enable_pull_requests_from_forks: false
  deployment_policy_branch: "production"
  enable_pe_plans: true
pipelines:
  main:
    triggers:
    - "COMMIT"
    stages:
    - name: "Code Validation stage"
      steps:
      - type: "JOB"
        name: "control-repo-manifest-validate"
        concurrent_compilations: 0
        all_deployments: false
      - type: "JOB"
        name: "control-repo-hiera-syntax-validate"
        concurrent_compilations: 0
        all_deployments: false
      - type: "JOB"
        name: "control-repo-template-syntax-validate"
        concurrent_compilations: 0
        all_deployments: false
      - type: "JOB"
        name: "control-repo-puppetfile-syntax-validate"
        concurrent_compilations: 0
        all_deployments: false
      auto_promote: "all_succeeded"
    - name: "Impact Analysis stage"
      steps:
      - type: "IMPACT_ANALYSIS"
        concurrent_compilations: 10
        all_deployments: true
      - type: "PULL_REQUEST_GATE"
        concurrent_compilations: 0
        all_deployments: false
      auto_promote: "all_succeeded"
    - name: "Deployment stage"
      steps:
      - type: "DEPLOYMENT"
        name: "Deployment to production on PE2"
        policy:
          name: "cd4pe_deployments::direct"
        parameters:
          noop: false
          fail_if_no_nodes: true
        timeout: 3600000
        concurrent_compilations: 0
        all_deployments: false
        pe_server: "PE2"
        target:
          type: "NODE_GROUP"
          node_group_id: "f4c28f60-083e-4a84-a514-8b8fc19a81d3"
      auto_promote: "all_succeeded"
    - name: "secret"
      steps:
      - type: "JOB"
        name: "secret-test"
        concurrent_compilations: 0
        all_deployments: false
      auto_promote: false
spec_version: "V1"

